
services:
  api:
    build: ./backend
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/optical-api:${TAG:-dev}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on: [db]
  ui:
    build: ./frontend
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/optical-ui:${TAG:-dev}
    restart: unless-stopped
    depends_on: [api]
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
