services:
  backend:
    image: ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPOSITORY_NAME}/${GITHUB_IMAGE_BACKEND}:${VERSION_BACKEND}
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on: []
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - pdf_output_data:/freedom-label-app/app/services/pdf_output
    # privileged: true # If permissions to USB are an issue, you can try privileged.

  frontend:
    image: ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPOSITORY_NAME}/${GITHUB_IMAGE_FRONTEND}:${VERSION_FRONTEND}
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      [backend]
      # backend:
      #   condition: service_healthy
    security_opt:
      - no-new-privileges:true

volumes:
  pdf_output_data:
