services:
  backend:
    image: ghcr.io/nico/freedom-label/backend:latest # Replace 'latest' with the desired semantic version
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
