name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Semantic Version Tag (e.g., v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/bake-action@v4
        with:
          files: ./docker-compose.yml
          targets: api,ui
          platform: linux/arm/v7,linux/amd64
          push: true
          set: | # Set the TAG variable for the images
            *.image=ghcr.io/${{ github.repository_owner }}/optical-api:${{ github.event.inputs.tag }}
            *.image=ghcr.io/${{ github.repository_owner }}/optical-ui:${{ github.event.inputs.tag }}
            *.image=ghcr.io/${{ github.repository_owner }}/optical-api:latest
            *.image=ghcr.io/${{ github.repository_owner }}/optical-ui:latest

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_SSH_HOST }}
          username: ${{ secrets.PI_SSH_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /path/to/your/app # Adjust this path on your Pi
            ./deploy/docker-rollout.sh
